// Palavras expandidas para Forca Bíblica (100+ palavras)
export const HANGMAN_WORDS_EXPANDED = [
  { word: "GENESIS", hint: "Primeiro livro da Bíblia", category: "Livros" },
  { word: "EXODO", hint: "Livro da saída do Egito", category: "Livros" },
  { word: "LEVITICO", hint: "Livro sobre leis de Israel", category: "Livros" },
  { word: "NUMEROS", hint: "Livro do censo de Israel", category: "Livros" },
  { word: "DEUTERONOMIO", hint: "Livro da segunda lei", category: "Livros" },
  { word: "JOSUE", hint: "Livro da conquista de Canaã", category: "Livros" },
  { word: "JUIZES", hint: "Livro dos juízes de Israel", category: "Livros" },
  { word: "RUTE", hint: "Livro de amor e redenção", category: "Livros" },
  { word: "SAMUEL", hint: "Livro sobre o profeta Samuel", category: "Livros" },
  { word: "REIS", hint: "Livro dos reis de Israel", category: "Livros" },
  { word: "CRONICAS", hint: "Livro de história de Israel", category: "Livros" },
  { word: "ESDRAS", hint: "Livro do retorno do exílio", category: "Livros" },
  { word: "NEEMIAS", hint: "Livro da reconstrução de Jerusalém", category: "Livros" },
  { word: "JO", hint: "Livro sobre sofrimento e fé", category: "Livros" },
  { word: "SALMOS", hint: "Livro de louvores e orações", category: "Livros" },
  { word: "PROVERBIOS", hint: "Livro da sabedoria de Salomão", category: "Livros" },
  { word: "ECLESIASTES", hint: "Livro sobre a vida sob o sol", category: "Livros" },
  { word: "CANTARES", hint: "Livro de poesia de amor", category: "Livros" },
  { word: "ISAIAS", hint: "Profeta que profetizou sobre Jesus", category: "Livros" },
  { word: "JEREMIAS", hint: "Profeta do choro", category: "Livros" },
  { word: "LAMENTACOES", hint: "Livro de lamentos de Jeremias", category: "Livros" },
  { word: "EZEQUIEL", hint: "Profeta das visões", category: "Livros" },
  { word: "DANIEL", hint: "Profeta no exílio babilônico", category: "Livros" },
  { word: "OSEIAS", hint: "Profeta do amor de Deus", category: "Livros" },
  { word: "JOEL", hint: "Profeta do derramamento do Espírito", category: "Livros" },
  { word: "AMOS", hint: "Profeta da justiça", category: "Livros" },
  { word: "OBADIAS", hint: "Profeta mais curto da Bíblia", category: "Livros" },
  { word: "JONAS", hint: "Profeta engolido por peixe", category: "Livros" },
  { word: "MIQUEIAS", hint: "Profeta sobre o julgamento", category: "Livros" },
  { word: "NAUM", hint: "Profeta sobre Nínive", category: "Livros" },
  { word: "HABACUQUE", hint: "Profeta que questionou Deus", category: "Livros" },
  { word: "SOFONIAS", hint: "Profeta do dia do Senhor", category: "Livros" },
  { word: "AGEU", hint: "Profeta da reconstrução do Templo", category: "Livros" },
  { word: "ZACARIAS", hint: "Profeta de esperança", category: "Livros" },
  { word: "MALAQUIAS", hint: "Último profeta do Antigo Testamento", category: "Livros" },
  { word: "MATEUS", hint: "Evangelho para os judeus", category: "Livros" },
  { word: "MARCOS", hint: "Evangelho mais curto", category: "Livros" },
  { word: "LUCAS", hint: "Evangelho detalhado", category: "Livros" },
  { word: "JOAO", hint: "Evangelho espiritual", category: "Livros" },
  { word: "ATOS", hint: "Livro dos apóstolos", category: "Livros" },
  { word: "ROMANOS", hint: "Carta sobre a fé", category: "Livros" },
  { word: "CORINTIOS", hint: "Cartas sobre problemas da igreja", category: "Livros" },
  { word: "GALATAS", hint: "Carta sobre a liberdade cristã", category: "Livros" },
  { word: "EFESIOS", hint: "Carta sobre a Igreja", category: "Livros" },
  { word: "FILIPENSES", hint: "Carta de alegria", category: "Livros" },
  { word: "COLOSSENSES", hint: "Carta sobre Cristo", category: "Livros" },
  { word: "TESSALONICENSES", hint: "Cartas sobre a volta de Cristo", category: "Livros" },
  { word: "TIMOTEO", hint: "Cartas pastorais", category: "Livros" },
  { word: "TITO", hint: "Carta pastoral", category: "Livros" },
  { word: "FILEMOM", hint: "Carta pessoal", category: "Livros" },
  { word: "HEBREUS", hint: "Carta sobre Cristo e a Lei", category: "Livros" },
  { word: "TIAGO", hint: "Carta sobre a fé e obras", category: "Livros" },
  { word: "PEDRO", hint: "Cartas sobre sofrimento", category: "Livros" },
  { word: "APOCALIPSE", hint: "Último livro da Bíblia", category: "Livros" },
  { word: "ABRAAO", hint: "Pai da fé", category: "Personagens" },
  { word: "SARA", hint: "Esposa de Abraão", category: "Personagens" },
  { word: "ISAQUE", hint: "Filho de Abraão", category: "Personagens" },
  { word: "JACO", hint: "Pai das doze tribos", category: "Personagens" },
  { word: "RAQUEL", hint: "Esposa de Jacó", category: "Personagens" },
  { word: "LEA", hint: "Primeira esposa de Jacó", category: "Personagens" },
  { word: "JOSE", hint: "Vendido pelos irmãos", category: "Personagens" },
  { word: "BENJAMIN", hint: "Filho mais novo de Jacó", category: "Personagens" },
  { word: "MOISES", hint: "Libertador de Israel", category: "Personagens" },
  { word: "ARAO", hint: "Irmão de Moisés", category: "Personagens" },
  { word: "MIRIAM", hint: "Irmã de Moisés", category: "Personagens" },
  { word: "DAVI", hint: "Rei pastor que matou Golias", category: "Personagens" },
  { word: "SALOMAO", hint: "Rei mais sábio de Israel", category: "Personagens" },
  { word: "ELIAS", hint: "Profeta levado ao céu em carro de fogo", category: "Personagens" },
  { word: "ELISEU", hint: "Discípulo de Elias", category: "Personagens" },
  { word: "SANSAO", hint: "Juiz conhecido por sua força", category: "Personagens" },
  { word: "DALILA", hint: "Mulher que traiu Sansão", category: "Personagens" },
  { word: "DEBORA", hint: "Juíza e profetisa de Israel", category: "Personagens" },
  { word: "GIDEAO", hint: "Juiz que derrotou os midianitas", category: "Personagens" },
  { word: "SAMUEL", hint: "Profeta que ungiu Davi", category: "Personagens" },
  { word: "SAUL", hint: "Primeiro rei de Israel", category: "Personagens" },
  { word: "RAABE", hint: "Prostituta que escondeu os espias", category: "Personagens" },
  { word: "NOEMI", hint: "Sogra de Rute", category: "Personagens" },
  { word: "BOAZ", hint: "Marido de Rute", category: "Personagens" },
  { word: "MARIA", hint: "Mãe de Jesus", category: "Personagens" },
  { word: "JOSE", hint: "Pai terreno de Jesus", category: "Personagens" },
  { word: "JESUS", hint: "Salvador do mundo", category: "Personagens" },
  { word: "JOAO", hint: "Discípulo amado de Jesus", category: "Personagens" },
  { word: "PAULO", hint: "Apóstolo dos gentios", category: "Personagens" },
  { word: "JUDAS", hint: "Traiu Jesus por 30 moedas", category: "Personagens" },
  { word: "TIAGO", hint: "Apóstolo e irmão de João", category: "Personagens" },
  { word: "ANDRE", hint: "Apóstolo e irmão de Pedro", category: "Personagens" },
  { word: "FILIPE", hint: "Um dos 12 apóstolos", category: "Personagens" },
  { word: "BARTOLOMEU", hint: "Apóstolo também chamado Natanael", category: "Personagens" },
  { word: "TOME", hint: "Apóstolo que duvidou", category: "Personagens" },
  { word: "JERUSALEM", hint: "Cidade santa de Israel", category: "Lugares" },
  { word: "BELEM", hint: "Cidade onde Jesus nasceu", category: "Lugares" },
  { word: "NAZARE", hint: "Cidade onde Jesus cresceu", category: "Lugares" },
  { word: "EGITO", hint: "País onde Israel foi escravo", category: "Lugares" },
  { word: "JORDAO", hint: "Rio onde Jesus foi batizado", category: "Lugares" },
  { word: "SINAI", hint: "Monte onde Moisés recebeu os mandamentos", category: "Lugares" },
  { word: "CALVARIO", hint: "Local onde Jesus foi crucificado", category: "Lugares" },
  { word: "EDEN", hint: "Jardim onde Adão e Eva viviam", category: "Lugares" },
  { word: "BABILONIA", hint: "Império que levou Israel ao cativeiro", category: "Lugares" },
  { word: "GALILEIA", hint: "Região onde Jesus realizou muitos milagres", category: "Lugares" },
  { word: "JERICO", hint: "Cidade cuja muralha caiu", category: "Lugares" },
  { word: "ANTIOQUIA", hint: "Cidade onde os discípulos foram chamados cristãos", category: "Lugares" },
  { word: "CORINTO", hint: "Cidade onde Paulo pregou", category: "Lugares" },
  { word: "EFESO", hint: "Cidade onde Paulo passou tempo", category: "Lugares" },
  { word: "ROMA", hint: "Capital do Império Romano", category: "Lugares" },
  { word: "ATENAS", hint: "Cidade onde Paulo pregou no Areópago", category: "Lugares" },
  { word: "PATMOS", hint: "Ilha onde João recebeu o Apocalipse", category: "Lugares" },
  { word: "CAFARNAUM", hint: "Cidade onde Jesus baseou seu ministério", category: "Lugares" },
  { word: "SAMARIA", hint: "Região entre Judeia e Galileia", category: "Lugares" },
  { word: "BATISMO", hint: "Sacramento de iniciação cristã", category: "Conceitos" },
  { word: "RESSURREICAO", hint: "Jesus voltou à vida no terceiro dia", category: "Conceitos" },
  { word: "PENTECOSTES", hint: "Dia em que o Espírito Santo desceu", category: "Conceitos" },
  { word: "ALIANCA", hint: "Pacto entre Deus e seu povo", category: "Conceitos" },
  { word: "PROFECIA", hint: "Mensagem divina sobre o futuro", category: "Conceitos" },
  { word: "TABERNACULO", hint: "Santuário portátil de Israel no deserto", category: "Conceitos" },
  { word: "MILAGRE", hint: "Ato sobrenatural de Deus", category: "Conceitos" },
  { word: "EVANGELHO", hint: "Boas novas de Jesus Cristo", category: "Conceitos" },
  { word: "APOSTOLO", hint: "Enviado por Jesus para pregar", category: "Conceitos" },
  { word: "PROFETA", hint: "Mensageiro de Deus", category: "Conceitos" },
  { word: "TEMPLO", hint: "Casa de Deus em Jerusalém", category: "Conceitos" },
  { word: "SINAGOGA", hint: "Lugar de adoração judaica", category: "Conceitos" },
  { word: "SACRIFICIO", hint: "Oferenda a Deus no Templo", category: "Conceitos" },
  { word: "REDENÇÃO", hint: "Salvação através de Jesus", category: "Conceitos" },
  { word: "GRAÇA", hint: "Favor imerecido de Deus", category: "Conceitos" },
  { word: "AMOR", hint: "Maior mandamento de Jesus", category: "Conceitos" },
  { word: "PERDÃO", hint: "Libertação da culpa", category: "Conceitos" },
  { word: "ARREPENDIMENTO", hint: "Mudança de mente e coração", category: "Conceitos" },
  { word: "ORAÇÃO", hint: "Comunicação com Deus", category: "Conceitos" },
  { word: "JEJUM", hint: "Abstinência de comida por devoção", category: "Conceitos" },
  { word: "ADORAÇÃO", hint: "Reverência a Deus", category: "Conceitos" },
];
