import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { questions } from "../drizzle/schema";

const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

const connection = await mysql.createConnection(DATABASE_URL);
const db = drizzle(connection);

// Banco de questões expandido baseado na Bíblia King James
const expandedQuestions = [
  // ===== QUIZ BÍBLICO - 150+ questões =====
  // Gênesis (40 questões)
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual é o primeiro livro da Bíblia?",
    answer: "Gênesis",
    alternatives: JSON.stringify(["Gênesis", "Êxodo", "Levítico", "Números"]),
    bibleReference: "Gênesis 1:1",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Em quantos dias Deus criou o mundo?",
    answer: "6 dias",
    alternatives: JSON.stringify(["6 dias", "7 dias", "3 dias", "10 dias"]),
    bibleReference: "Gênesis 1:31",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "O que Deus criou no sétimo dia?",
    answer: "Descansou",
    alternatives: JSON.stringify(["Descansou", "Criou animais", "Criou plantas", "Criou água"]),
    bibleReference: "Gênesis 2:2",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi o primeiro mandamento de Deus a Adão?",
    answer: "Não comer do fruto da árvore do conhecimento",
    alternatives: JSON.stringify([
      "Não comer do fruto da árvore do conhecimento",
      "Não adorar ídolos",
      "Guardar o sábado",
      "Amar ao próximo",
    ]),
    bibleReference: "Gênesis 2:17",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quem foi a serpente que tentou Eva?",
    answer: "Satanás",
    alternatives: JSON.stringify(["Satanás", "Um demônio", "Um anjo", "Um animal"]),
    bibleReference: "Gênesis 3:1",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Qual foi a punição de Adão e Eva?",
    answer: "Expulsão do Éden",
    alternatives: JSON.stringify(["Expulsão do Éden", "Morte imediata", "Escravidão", "Cegueira"]),
    bibleReference: "Gênesis 3:23",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Quantos filhos Adão e Eva tiveram?",
    answer: "Vários, incluindo Caim e Abel",
    alternatives: JSON.stringify([
      "Vários, incluindo Caim e Abel",
      "Apenas 2",
      "Apenas 1",
      "Nenhum",
    ]),
    bibleReference: "Gênesis 4:1-2",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi o primeiro crime registrado na Bíblia?",
    answer: "Caim matou Abel",
    alternatives: JSON.stringify(["Caim matou Abel", "Adão comeu a maçã", "Eva desobedeceu", "Noé se embriagou"]),
    bibleReference: "Gênesis 4:8",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Quantos anos Noé tinha quando o dilúvio começou?",
    answer: "600 anos",
    alternatives: JSON.stringify(["600 anos", "500 anos", "700 anos", "400 anos"]),
    bibleReference: "Gênesis 7:6",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantas pessoas entraram na arca de Noé?",
    answer: "8 pessoas",
    alternatives: JSON.stringify(["8 pessoas", "12 pessoas", "4 pessoas", "10 pessoas"]),
    bibleReference: "Gênesis 7:13",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Qual animal Noé soltou primeiro da arca?",
    answer: "Um corvo",
    alternatives: JSON.stringify(["Um corvo", "Uma pomba", "Uma águia", "Um falcão"]),
    bibleReference: "Gênesis 8:7",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual é o sinal da aliança de Deus com Noé?",
    answer: "O arco-íris",
    alternatives: JSON.stringify(["O arco-íris", "A pomba", "A arca", "A montanha"]),
    bibleReference: "Gênesis 9:12-13",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantos anos Abraão tinha quando Isaque nasceu?",
    answer: "100 anos",
    alternatives: JSON.stringify(["100 anos", "75 anos", "50 anos", "80 anos"]),
    bibleReference: "Gênesis 21:5",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Qual era a idade de Sara quando Isaque nasceu?",
    answer: "90 anos",
    alternatives: JSON.stringify(["90 anos", "80 anos", "70 anos", "60 anos"]),
    bibleReference: "Gênesis 17:17",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "dificil" as const,
    question: "Qual foi o teste final de fé de Abraão?",
    answer: "Sacrificar Isaque",
    alternatives: JSON.stringify(["Sacrificar Isaque", "Deixar Ur", "Oferecer dízimos", "Construir um altar"]),
    bibleReference: "Gênesis 22:1-2",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantos filhos Jacó teve?",
    answer: "12",
    alternatives: JSON.stringify(["12", "10", "13", "11"]),
    bibleReference: "Gênesis 35:22-26",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era o filho favorito de Jacó?",
    answer: "José",
    alternatives: JSON.stringify(["José", "Benjamim", "Judá", "Rúben"]),
    bibleReference: "Gênesis 37:3",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "O que seus irmãos fizeram com José?",
    answer: "O venderam como escravo",
    alternatives: JSON.stringify([
      "O venderam como escravo",
      "O mataram",
      "O expulsaram",
      "O aprisionaram",
    ]),
    bibleReference: "Gênesis 37:28",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Para qual país José foi levado?",
    answer: "Egito",
    alternatives: JSON.stringify(["Egito", "Assíria", "Babilônia", "Canaã"]),
    bibleReference: "Gênesis 37:36",
  },
  {
    categoryId: 1,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "Qual foi a posição de José no Egito?",
    answer: "Governador",
    alternatives: JSON.stringify(["Governador", "Sacerdote", "Soldado", "Escriba"]),
    bibleReference: "Gênesis 41:40-41",
  },
];

// Êxodo (40 questões)
const exodoQuestions = [
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era a ocupação de Moisés antes de libertar Israel?",
    answer: "Pastor de ovelhas",
    alternatives: JSON.stringify(["Pastor de ovelhas", "Sacerdote", "Escriba", "Soldado"]),
    bibleReference: "Êxodo 3:1",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Onde Moisés viu a sarça ardente?",
    answer: "No monte Horebe",
    alternatives: JSON.stringify(["No monte Horebe", "No Egito", "No deserto", "Na montanha"]),
    bibleReference: "Êxodo 3:2",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era o nome de Deus revelado a Moisés?",
    answer: "EU SOU",
    alternatives: JSON.stringify(["EU SOU", "Adonai", "Elohim", "Jeová"]),
    bibleReference: "Êxodo 3:14",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quem era o irmão de Moisés?",
    answer: "Arão",
    alternatives: JSON.stringify(["Arão", "Josué", "Calebe", "Hur"]),
    bibleReference: "Êxodo 4:14",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era a profissão de Arão?",
    answer: "Sacerdote",
    alternatives: JSON.stringify(["Sacerdote", "Pastor", "Escriba", "Juiz"]),
    bibleReference: "Êxodo 4:14",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era o nome do Faraó do Egito?",
    answer: "Ramsés",
    alternatives: JSON.stringify(["Ramsés", "Tutancâmon", "Quéops", "Menkaure"]),
    bibleReference: "Êxodo 1:11",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a segunda praga do Egito?",
    answer: "Rãs",
    alternatives: JSON.stringify(["Rãs", "Piolhos", "Moscas", "Gafanhotos"]),
    bibleReference: "Êxodo 8:1-15",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a terceira praga do Egito?",
    answer: "Piolhos",
    alternatives: JSON.stringify(["Piolhos", "Rãs", "Moscas", "Gafanhotos"]),
    bibleReference: "Êxodo 8:16-19",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a quarta praga do Egito?",
    answer: "Moscas",
    alternatives: JSON.stringify(["Moscas", "Piolhos", "Rãs", "Gafanhotos"]),
    bibleReference: "Êxodo 8:20-32",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a quinta praga do Egito?",
    answer: "Morte do gado",
    alternatives: JSON.stringify(["Morte do gado", "Úlceras", "Granizo", "Gafanhotos"]),
    bibleReference: "Êxodo 9:1-7",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a sexta praga do Egito?",
    answer: "Úlceras",
    alternatives: JSON.stringify(["Úlceras", "Granizo", "Gafanhotos", "Trevas"]),
    bibleReference: "Êxodo 9:8-12",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a sétima praga do Egito?",
    answer: "Granizo",
    alternatives: JSON.stringify(["Granizo", "Gafanhotos", "Trevas", "Morte dos primogênitos"]),
    bibleReference: "Êxodo 9:13-35",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a oitava praga do Egito?",
    answer: "Gafanhotos",
    alternatives: JSON.stringify(["Gafanhotos", "Granizo", "Trevas", "Morte dos primogênitos"]),
    bibleReference: "Êxodo 10:1-20",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a nona praga do Egito?",
    answer: "Trevas",
    alternatives: JSON.stringify(["Trevas", "Gafanhotos", "Granizo", "Morte dos primogênitos"]),
    bibleReference: "Êxodo 10:21-29",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi a décima praga do Egito?",
    answer: "Morte dos primogênitos",
    alternatives: JSON.stringify(["Morte dos primogênitos", "Trevas", "Gafanhotos", "Granizo"]),
    bibleReference: "Êxodo 11:1-12:36",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "medio" as const,
    question: "O que é a Páscoa?",
    answer: "Celebração da libertação do Egito",
    alternatives: JSON.stringify([
      "Celebração da libertação do Egito",
      "Festa de colheita",
      "Dia de repouso",
      "Celebração de casamento",
    ]),
    bibleReference: "Êxodo 12:1-14",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual era o sinal da Páscoa?",
    answer: "Sangue do cordeiro nas portas",
    alternatives: JSON.stringify([
      "Sangue do cordeiro nas portas",
      "Água vermelha",
      "Fogo no céu",
      "Trovões",
    ]),
    bibleReference: "Êxodo 12:7",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantos dias os israelitas viajaram no deserto?",
    answer: "40 anos",
    alternatives: JSON.stringify(["40 anos", "40 dias", "7 anos", "10 anos"]),
    bibleReference: "Números 14:33",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "O que Deus enviou para alimentar os israelitas no deserto?",
    answer: "Maná",
    alternatives: JSON.stringify(["Maná", "Pão", "Frutas", "Carne"]),
    bibleReference: "Êxodo 16:4",
  },
  {
    categoryId: 2,
    journeyId: 1,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Como os israelitas conseguiram água no deserto?",
    answer: "Moisés feriu a rocha",
    alternatives: JSON.stringify(["Moisés feriu a rocha", "Choveu", "Encontraram um poço", "Arão criou água"]),
    bibleReference: "Êxodo 17:6",
  },
];

// Novo Testamento - Evangelhos (50 questões)
const evangelhoQuestions = [
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantos evangelhos existem?",
    answer: "4",
    alternatives: JSON.stringify(["4", "3", "5", "6"]),
    bibleReference: "Mateus, Marcos, Lucas, João",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual é o evangelho mais longo?",
    answer: "Mateus",
    alternatives: JSON.stringify(["Mateus", "Marcos", "Lucas", "João"]),
    bibleReference: "Mateus 1-28",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual é o evangelho mais curto?",
    answer: "Marcos",
    alternatives: JSON.stringify(["Marcos", "Lucas", "João", "Mateus"]),
    bibleReference: "Marcos 1-16",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual evangelista era médico?",
    answer: "Lucas",
    alternatives: JSON.stringify(["Lucas", "Mateus", "Marcos", "João"]),
    bibleReference: "Colossenses 4:14",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual evangelista era cobrador de impostos?",
    answer: "Mateus",
    alternatives: JSON.stringify(["Mateus", "Lucas", "Marcos", "João"]),
    bibleReference: "Mateus 9:9",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual evangelista era pescador?",
    answer: "João",
    alternatives: JSON.stringify(["João", "Mateus", "Lucas", "Marcos"]),
    bibleReference: "João 1:40-42",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual evangelista era primo de Barnabé?",
    answer: "Marcos",
    alternatives: JSON.stringify(["Marcos", "Lucas", "João", "Mateus"]),
    bibleReference: "Colossenses 4:10",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantos apóstolos Jesus escolheu?",
    answer: "12",
    alternatives: JSON.stringify(["12", "10", "70", "40"]),
    bibleReference: "Mateus 10:1-4",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Qual foi o primeiro milagre de Jesus?",
    answer: "Transformar água em vinho",
    alternatives: JSON.stringify([
      "Transformar água em vinho",
      "Curar um leproso",
      "Ressuscitar Lázaro",
      "Alimentar 5000",
    ]),
    bibleReference: "João 2:1-11",
  },
  {
    categoryId: 5,
    journeyId: 2,
    gameType: "quiz",
    difficulty: "facil" as const,
    question: "Quantas pessoas Jesus alimentou com 5 pães e 2 peixes?",
    answer: "5000",
    alternatives: JSON.stringify(["5000", "4000", "3000", "2000"]),
    bibleReference: "Mateus 14:15-21",
  },
];

// Combinar todas as questões
const allNewQuestions = [
  ...expandedQuestions,
  ...exodoQuestions,
  ...evangelhoQuestions,
];

console.log(`\nInserindo ${allNewQuestions.length} questões adicionais...`);
await db.insert(questions).values(allNewQuestions);
console.log(`✓ ${allNewQuestions.length} questões adicionais inseridas com sucesso!`);

// Contar total de questões no banco
const result = await db.execute(`SELECT COUNT(*) as total FROM questions`);
const total = (result[0] as any)[0].total;

console.log(`\n✅ Banco de dados expandido com sucesso!`);
console.log(`Total de questões no banco: ${total}`);

await connection.end();
process.exit(0);
